/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum TrustLevel {
  Untrusted = 'Untrusted',
  Trusted = 'Trusted',
  Admin = 'Admin'
}
export interface Decision {
  outcome: string
  message?: string
  code?: string
  matchedRule?: string
  askPrompt?: string
  policyVersion: string
}
export interface SandboxOutput {
  exitCode: number
  stdout: string
  stderr: string
}
export interface ExecuteOutcome {
  status: string
  output?: SandboxOutput
  decision?: Decision
  policyVersion: string
  sandboxType?: string
  receipt?: string
}
export interface Context {
  trustLevel?: TrustLevel
  agentId?: string
  sessionId?: string
  actor?: string
  workingDirectory?: string
}
export declare class Guard {
  static fromYaml(yaml: string): Guard
  static fromYamlFile(path: string): Guard
  /**
   * Set the Ed25519 signing key for provenance receipts.
   * The key must be a 32-byte hex-encoded string.
   */
  setSigningKey(hexKey: string): void
  check(tool: string, payload: string, options?: Context | undefined | null): Decision
  /**
   * High-level execution method.
   * Uses the default sandbox implementation.
   */
  execute(tool: string, payload: string, options?: Context | undefined | null): Promise<ExecuteOutcome>
  reload(yaml: string): void
  reloadFromYaml(yaml: string): void
  policyVersion(): string
  policyHash(): string
}
