/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum TrustLevel {
  Untrusted = 'Untrusted',
  Trusted = 'Trusted',
  Admin = 'Admin'
}
export interface Decision {
  outcome: string
  message?: string
  code?: string
  matchedRule?: string
  askPrompt?: string
  policyVersion: string
  policyVerificationStatus: string
  policyVerificationError?: string
}
export interface PolicyVerification {
  status: string
  error?: string
}
export interface SandboxOutput {
  exitCode: number
  stdout: string
  stderr: string
}
export interface ExecuteOutcome {
  status: string
  output?: SandboxOutput
  decision?: Decision
  policyVersion: string
  sandboxType?: string
  receipt?: string
  policyVerificationStatus: string
  policyVerificationError?: string
}
export interface Context {
  trustLevel?: TrustLevel
  agentId?: string
  sessionId?: string
  actor?: string
  workingDirectory?: string
}
/**
 * Normalize a raw input string into the payload format expected by the guard.
 * Shell tools (bash, shell, terminal) are wrapped as {"command": "..."}.
 * Other string inputs are wrapped as {"input": "..."}.
 */
export declare function normalizePayload(tool: string, rawInput: string): string
/**
 * Verify an Ed25519-signed execution receipt.
 * receipt_json: JSON string of the ExecutionReceipt.
 * public_key_hex: 64 hex chars (32 bytes) of the Ed25519 public key.
 */
export declare function verifyReceipt(receiptJson: string, publicKeyHex: string): boolean
export declare class Guard {
  static fromYaml(yaml: string): Guard
  static fromYamlFile(path: string): Guard
  static fromSignedYaml(yaml: string, publicKeyHex: string, signatureHex: string): Guard
  static fromSignedYamlFile(policyPath: string, publicKeyPath: string, signaturePath: string): Guard
  /**
   * Set the Ed25519 signing key for provenance receipts.
   * The key must be a 32-byte hex-encoded string.
   */
  setSigningKey(hexKey: string): void
  check(tool: string, payload: string, options?: Context | undefined | null): Decision
  /**
   * High-level execution method.
   * Uses the default sandbox implementation.
   */
  execute(tool: string, payload: string, options?: Context | undefined | null): Promise<ExecuteOutcome>
  reload(yaml: string): void
  reloadFromYaml(yaml: string): void
  policyVersion(): string
  policyHash(): string
  policyVerification(): PolicyVerification
}
